/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_aziz_window_login (void);
GtkWidget* create_aziz_window_admin (void);
GtkWidget* create_ines_window_modifier_election (void);
GtkWidget* create_ines_window_afficher_election (void);
GtkWidget* create_aziz_window_gestion_obs (void);
GtkWidget* create_ines_window_ajouter_election (void);
GtkWidget* create_aziz_window_ges_admin (void);
GtkWidget* create_saif_window_supprimer (void);
GtkWidget* create_chadha_window_login (void);
GtkWidget* create_ines_window_authentification (void);
GtkWidget* create_chadha_window_espace_electeur (void);
GtkWidget* create_chadha_window2_voter (void);
GtkWidget* create_chadha_window3_afficher_listes (void);
GtkWidget* create_chadha_window4_ajouter_list (void);
GtkWidget* create_chadha_window5_modifier_list (void);
GtkWidget* create_saif_window_aff (void);
GtkWidget* create_saif_window_aj (void);
GtkWidget* create_saif_window_mod (void);
GtkWidget* create_saif_window_login (void);
GtkWidget* create_ines_statistique (void);
GtkWidget* create_mediouni_recla_ajout (void);
GtkWidget* create_mediouni_recla_modif (void);
GtkWidget* create_mediouni_liste_recla (void);
