/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *aziz_window_login;
  GtkWidget *aziz_window_admin;
  GtkWidget *ines_window_modifier_election;
  GtkWidget *ines_window_afficher_election;
  GtkWidget *mediouni_recla_ajout;
  GtkWidget *mediouni_recla_modif;
  GtkWidget *mediouni_liste_recla;
  GtkWidget *aziz_window_gestion_obs;
  GtkWidget *ines_window_ajouter_election;
  GtkWidget *aziz_window_ges_admin;
  GtkWidget *mediouni_gestion_rec;
  GtkWidget *reclamation_supprimer;
  GtkWidget *saif_window_supprimer;
  GtkWidget *chadha_window_login;
  GtkWidget *ines_window_authentification;
  GtkWidget *chadha_window_espace_electeur;
  GtkWidget *chadha_window2_voter;
  GtkWidget *chadha_window3_afficher_listes;
  GtkWidget *chadha_window4_ajouter_list;
  GtkWidget *chadha_window5_modifier_list;
  GtkWidget *saif_window_aff;
  GtkWidget *saif_window_aj;
  GtkWidget *saif_window_mod;
  GtkWidget *saif_window_login;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("/home/aziz/Downloads/APP_isie_final(1)/APP_isie_final");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  aziz_window_login = create_aziz_window_login ();
  gtk_widget_show (aziz_window_login);
  //aziz_window_admin = create_aziz_window_admin ();
  //gtk_widget_show (aziz_window_admin);
  /*ines_window_modifier_election = create_ines_window_modifier_election ();
  gtk_widget_show (ines_window_modifier_election);
  ines_window_afficher_election = create_ines_window_afficher_election ();
  gtk_widget_show (ines_window_afficher_election);
  mediouni_recla_ajout = create_mediouni_recla_ajout ();
  gtk_widget_show (mediouni_recla_ajout);
  mediouni_recla_modif = create_mediouni_recla_modif ();
  gtk_widget_show (mediouni_recla_modif);*/
  /*mediouni_liste_recla = create_mediouni_liste_recla ();
  gtk_widget_show (mediouni_liste_recla);
  /*ines_window_ajouter_election = create_ines_window_ajouter_election ();
  gtk_widget_show (ines_window_ajouter_election);*/
  //aziz_window_ges_admin = create_aziz_window_ges_admin ();
  //gtk_widget_show (aziz_window_ges_admin);
  /*mediouni_gestion_rec = create_mediouni_gestion_rec ();
  gtk_widget_show (mediouni_gestion_rec);
  reclamation_supprimer = create_reclamation_supprimer ();
  gtk_widget_show (reclamation_supprimer);
  saif_window_supprimer = create_saif_window_supprimer ();
  gtk_widget_show (saif_window_supprimer);
  chadha_window_login = create_chadha_window_login ();
  gtk_widget_show (chadha_window_login);
  ines_window_authentification = create_ines_window_authentification ();
  gtk_widget_show (ines_window_authentification);
  chadha_window_espace_electeur = create_chadha_window_espace_electeur ();
  gtk_widget_show (chadha_window_espace_electeur);
  chadha_window2_voter = create_chadha_window2_voter ();
  gtk_widget_show (chadha_window2_voter);
  chadha_window3_afficher_listes = create_chadha_window3_afficher_listes ();
  gtk_widget_show (chadha_window3_afficher_listes);
  chadha_window4_ajouter_list = create_chadha_window4_ajouter_list ();
  gtk_widget_show (chadha_window4_ajouter_list);
  chadha_window5_modifier_list = create_chadha_window5_modifier_list ();
  gtk_widget_show (chadha_window5_modifier_list);
  saif_window_aff = create_saif_window_aff ();
  gtk_widget_show (saif_window_aff);
  saif_window_aj = create_saif_window_aj ();
  gtk_widget_show (saif_window_aj);
  saif_window_mod = create_saif_window_mod ();
  gtk_widget_show (saif_window_mod);
  saif_window_login = create_saif_window_login ();
  gtk_widget_show (saif_window_login);*/

  gtk_main ();
  return 0;
}

